### ISSUE TITLE
Add to cart

### ISSUE THREAD

**Issue by MarichkaTanchyn** [MarichkaTanchyn/Pizza_Test#1]
Dodać widoczną zmiane ilości produktów w koszyku 

<img width="396" alt="Screenshot 2021-11-03 at 19 38 18" src="https://user-images.githubusercontent.com/65307654/140173059-1e69a791-6caf-4f29-aa97-65508b78bcc3.png">

**Comment by S21010** [comment]
You propably should change font and size of numer
